### ISSUE TITLE
Pip package

### ISSUE THREAD

**Issue by hendrikschneider** [dimostenis/color-hash-python#1]
Hey, 

it would be awesome if this package could be installable via pip so that it is easy to integrate in a project.

**Comment by dimostenis** [comment]
Hey. Its on pypi, so you should be able to install it with `pip`, `poetry` etc with no problem.
I just tried it.

```
~/Downloads 
❯ python3.7 -m venv venv

~/Downloads took 2s 
❯ . venv/bin/activate

~/Downloads via 🐍 v3.7.10 (venv) 
❯ pip install colorhash
Collecting colorhash
  Downloading colorhash-1.0.4-py3-none-any.whl (5.5 kB)
Installing collected packages: colorhash
Successfully installed colorhash-1.0.4
```

**Comment by hendrikschneider** [comment]
Ah, thanks for your answer. I tried to use the package name if your readme "color-hash". Maybe a small addition with a pip install colorhash in the readme could be useful. I will open a pr tomorrow it that would be fine for you.

**Comment by dimostenis** [comment]
Good point. I will be happy if you do submit a PR.

**Comment by dimostenis** [comment]
I had some enhancements in my mind, so I did it and added along those missing installation instructions in https://github.com/dimostenis/color-hash-python/pull/2.

So anyway, thank you for pushing me!:)

**Comment by hendrikschneider** [comment]
Perfect, Thank you 👍
